<a href="https://colab.research.google.com/github/shivaprasannatejadharma-arch/ML_LAB_2026-27/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**NumPy Arrya Creation**

In [2]:
#create a list named list1
list1 = [2,4,6,8]

#create numpy array using list1
array1 = np.array(list1)

print(array1)

[2 4 6 8]


In [3]:
# create numpy array using a list
array1 = np.array([2, 4, 6, 8])
print(array1)

[2 4 6 8]



**Create a 2-D NumPy Array**

In [4]:
# create a 2D array with 2 rows and 4 columns
array1 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

print(array1)

[[1 2 3 4]
 [5 6 7 8]]



**Create a 3-D NumPy Array**

In [5]:
# create a 3D array with 2 "slices", each of 3 rows and 4 columns
array1 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

print(array1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


**Check Data Type of a NumPy Array**

In [6]:
# create an array of integers
array1 = np.array([2, 4, 6])

# check the data type of array1
print(array1.dtype)

int64


**Check dimensions of an Numpy Array**

In [7]:
print(array1.ndim)

1



**Check Size of Numpy array**

In [8]:


print(array1.size)

3



**NumPy Array shape Attribute**

In [9]:
array1 = np.array([[1, 2, 3],
                [6, 7, 8]])

# return a tuple that gives size of array in each dimension
print(array1.shape)

(2, 3)



**NumPy Array itemsize Attribute**

In [10]:

# create a default 1-D array of integers
array1 = np.array([6, 7, 8, 10, 13])

# create a 1-D array of 32-bit integers
array2 = np.array([6, 7, 8, 10, 13], dtype=np.int32)

# use of itemsize to determine size of each array element of array1 and array2
print(array1.itemsize)
print(array2.itemsize)


8
4


**NumPy Array data Attribute**

In [12]:
array1 = np.array([6, 7, 8])
array2 = np.array([[1, 2, 3],
                   	    [6, 7, 8]])

# print memory address of array1's and array2's data
print("\nData of array1 is: ",array1.data)
print("Data of array2 is: ",array2.data)


Data of array1 is:  <memory at 0x7a939d8d28c0>
Data of array2 is:  <memory at 0x7a939c1e8380>


**Access Array Elements Using Index**

In [13]:
array1 = np.array([1, 3, 5, 7, 9])

# access numpy elements using index
print(array1[0])
print(array1[2])
print(array1[4])


1
5
9


**Modify Array Elements Using Index**

In [14]:
array1[1]=10
print(array1)

[ 1 10  5  7  9]



**2-D NumPy Array Indexing**

In [15]:
# create a 2D array
array1 = np.array([[1, 3, 5, 7],
                       [9, 11, 13, 15],
                       [2, 4, 6, 8]])


# access the element at the second row and fourth column
element1 = array1[1, 3]  # returns 15
print("4th Element at 2nd Row:",element1)

# access the element at the first row and second column
element2 = array1[0, 1]  # returns 3
print("2nd Element at First Row:",element2)

4th Element at 2nd Row: 15
2nd Element at First Row: 3



**NumPy Statistical Functions**

In [16]:
# create a 1D array with 5 elements
array1 = np.array([1, 2, 3, 4, 5])

# calculate the median
median = np.median(array1)

print(median)

3.0


**Compute Mean Using NumPy**

In [17]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the mean of marks
mean_marks = np.mean(marks)

print(mean_marks)


77.2


**Standard Deviation of NumPy Array**

In [18]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.std(marks)
print(std_marks)

6.368673331236263



**Numpy Percentile**

In [19]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.percentile(marks,50)
print(std_marks)

78.0


**Numpy min**

In [20]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.min(marks)
print(std_marks)


66



**Numpy max**

In [21]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.max(marks)
print(std_marks)


85



**Array Arithmetic Operations**

In [22]:
# Import `numpy` as `np`
import numpy as np
x = np.array([[1, 2, 3], [3, 4, 5]])
y = np.array([6,7,8])

# Add `x` and `y`
z = np.add(x,y)
print("Addition of x and y:\n", z)

# Subtract `x` and `y`
z = np.subtract(x,y)
print("Subtraction of y from x:\n", z)

# Multiply `x` and `y`
z = np.multiply(x,y)
print("Element-wise multiplication of x and y:\n", z)

Addition of x and y:
 [[ 7  9 11]
 [ 9 11 13]]
Subtraction of y from x:
 [[-5 -5 -5]
 [-3 -3 -3]]
Element-wise multiplication of x and y:
 [[ 6 14 24]
 [18 28 40]]


**Append Arrays**

In [23]:
import numpy as np

my_array = np.array([1,2,3,4])

# Print `my_array` before appending
print("my_array before appending:", my_array)

# Append a 1D array to `my_array`
new_array = np.append(my_array, [7, 8, 9, 10])

# Print `new_array`
print("new_array:", new_array)

# Print `my_array` after appending
print("my_array after appending:", my_array)

my_array before appending: [1 2 3 4]
new_array: [ 1  2  3  4  7  8  9 10]
my_array after appending: [1 2 3 4]


**Appending to my_2d_array:**

In [24]:
import numpy as np

my_2d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# Print `my_2d_array` before appending
print("my_2d_array before appending:\n", my_2d_array)

# Append an extra column to `my_2d_array`
new_2d_array = np.append(my_2d_array, [[7], [8]], axis=1)

# Print `new_2d_array`
print("new_2d_array:\n", new_2d_array)

# Print `my_2d_array` after appending
print("my_2d_array after appending:\n", my_2d_array)


my_2d_array before appending:
 [[1 2 3 4]
 [5 6 7 8]]
new_2d_array:
 [[1 2 3 4 7]
 [5 6 7 8 8]]
my_2d_array after appending:
 [[1 2 3 4]
 [5 6 7 8]]


**Insert and Delete Array Elements**

In [25]:
import numpy as np
my_array = np.array([1,2,3,4])
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# Insert `5` at index 1
np.insert(my_array, 1, 5)

# Delete the value at index 1
np.delete(my_array,[1])

array([1, 3, 4])